/vis/open OGL 1200x800
/vis/drawVolume

/vis/viewer/set/viewpointThetaPhi 80 20
/vis/viewer/set/lightsThetaPhi    45 45
/vis/viewer/zoom 1.2

/vis/scene/add/axes 0 0 0 500 mm

# Show all daughters — essential for seeing individual straws
/vis/geometry/set/visibility World 0 false
/vis/viewer/set/hiddenMarker true

/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate 100
/run/beamOn 0



